#!/bin/bash

cd ~/call_for_code/project

echo "stopping containers..."

docker-compose down
    
echo "pulling from master..."

git pull origin master

echo "pulled successfully..."

echo "rebuilding containers"

docker-compose up --build -d && echo "containers started"